site_name: Dwayne Jones
site_author: Dwayne Jones
site_description: >-
  AI Consulting, Multi-Modal Computer Vision and Inverse Graphics
repo_name: blog
repo_url: https://github.com/dwaynekj/blog/
site_url: https://dwaynekj.dev
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2025 Dwayne Jones 
theme:
  name: material
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
    theme:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette:
      - scheme: youtube
  font:
    text: Roboto
    code: Roboto Mono
# Extensions
markdown_extensions:
  - abbr
  - admonition
  - pymdownx.details
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: dwaynekj 
      repo: instructor
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      auto_append:
        - includes/mkdocs.md
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
nav:
  - Home: 
    - Introductions: 'index.md'
    - Books: 'young-adult.md'
  # - Learn to TBD: "TBD.md"
  - Consulting:
    - Consulting Services: "services.md"
    - Jump on a Call: "expert-calls.md"
  # - Job Board: ""
  - Writing:
    - "writing/index.md"
plugins:
  - social
  # - rss:
  #     match_path: "writing/posts/.*"
  #     skip_ci_warning: true
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - mkdocstrings:
      handlers:
        python:
          options:
            members_order: alphabetical
            allow_inspection: true
            show_bases: true
  - blog:
      enabled: !ENV CI
      blog_dir: writing
      blog_toc: true
      post_dir: writing/posts
      post_date_format: yyyy/MM/dd
      post_url_format: "{date}/{slug}"
      authors_file: "{blog}/.authors.yml"
extra:
  analytics:
    provider: google
    property: G-DQD9Z7GLZ1
  social:
    - icon: fontawesome/solid/rss
      link: feed_rss_created.xml
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/dwaynekj
    - icon: fontawesome/brands/twitter
      link: https://x.com/senojenyawd
    - icon: fontawesome/brands/youtube
      link: https://youtube.com/@dwaynekj
    - icon: fontawesome/brands/github
      link: https://github.com/dwaynekj
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/dwayne-khallique-jones-53821226
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/mathjax.js
  - javascripts/posthog-analytics.js
  - https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
copyright: Copyright &copy; 2025 Dwayne Jones
