authors:
  dwaynekj:
    name: Dwayne Jones
    description: Creator
    avatar: https://avatars.githubusercontent.com/dwaynekj
    url: https://www.instagram.com/dwaynekj/
    # url: https://x.com/intent/follow?screen_name=senojenyawd
